networks:
  ec2-play:
    driver: bridge

volumes:
  ec2-play_node_modules:
  ec2-play_lib:

services:  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api_image
    container_name: ec2-play_api
    working_dir: /home/ec2-play
    ports:
      - 8848:8848
    volumes:
      - .:/home/ec2-play
      - ec2-play_node_modules:/home/ec2-play/node_modules
      - ec2-play_lib:/home/ec2-play/lib
    networks:
      - ec2-play
  
  webserver:
    image: nginx:alpine
    container_name: ec2-play_webserver
    depends_on:
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - ec2-play
